Controllers/CompteController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MedManager.Models;
using MedManager.ViewModel.Compte;

namespace MedManager.Controllers
{
	public class CompteController : Controller
	{
		private readonly SignInManager<Medecin> _gestionConnexion;
		private readonly UserManager<Medecin> _gestionUtilisateurs;
		private readonly ILogger<CompteController> _logger;

		public CompteController(SignInManager<Medecin> gestionConnexion, UserManager<Medecin> gestionUtilisateurs, ILogger<CompteController> logger)
		{
			_gestionConnexion = gestionConnexion;
			_gestionUtilisateurs = gestionUtilisateurs;
			_logger = logger;
		}

		[HttpGet]
		public IActionResult Connexion()
		{
			_logger.LogInformation("Affichage de la page de connexion.");
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Connexion(ConnexionViewModel modele)
		{
			_logger.LogInformation("Tentative de connexion pour l'utilisateur {NomUtilisateur}.", modele.NomUtilisateur);

			if (ModelState.IsValid)
			{
				try
				{
					var resultat = await _gestionConnexion.PasswordSignInAsync(modele.NomUtilisateur, modele.MotDePasse, modele.SeRappelerDeMoi, false);

					if (resultat.Succeeded)
					{
						_logger.LogInformation("Connexion réussie pour l'utilisateur {NomUtilisateur}.", modele.NomUtilisateur);
						return RedirectToAction("Index", "Tableaudebord");
					}

					_logger.LogWarning("Échec de connexion pour l'utilisateur {NomUtilisateur}. Mot de passe ou nom incorrect.", modele.NomUtilisateur);
				}
				catch (Exception ex)
				{
					_logger.LogError(ex, "Erreur lors de la tentative de connexion pour l'utilisateur {NomUtilisateur}.", modele.NomUtilisateur);
					ModelState.AddModelError("", "Une erreur est survenue lors de la tentative de connexion.");
				}
			}

			return View(modele);
		}

		public async Task<IActionResult> Deconnexion()
		{
			try
			{
				_logger.LogInformation("Déconnexion en cours.");
				await _gestionConnexion.SignOutAsync();
				_logger.LogInformation("Déconnexion réussie.");
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Erreur lors de la tentative de déconnexion.");
                return RedirectToAction("Index", "Error");
            }

			return RedirectToAction("Index", "Accueil");
		}

		public IActionResult Inscription()
		{
			_logger.LogInformation("Affichage de la page d'inscription.");
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Inscription(CompteViewModel modele)
		{
			_logger.LogInformation("Tentative d'inscription pour l'utilisateur {NomUtilisateur}.", modele.NomUtilisateur);

			if (ModelState.IsValid)
			{
				try
				{
					var utilisateur = new Medecin
					{
						UserName = modele.NomUtilisateur,
						Email = modele.Email,
						Nom = modele.Nom,
						Prenom = modele.Prenom,
						Ville = modele.Ville,
						Adresse = modele.Adresse,
						Faculte = modele.Faculte,
						Specialite = modele.Specialite,
						NumeroTel = modele.MotDePasse,
					};

					var resultat = await _gestionUtilisateurs.CreateAsync(utilisateur, modele.MotDePasse);

					if (resultat.Succeeded)
					{
						_logger.LogInformation("Inscription réussie pour l'utilisateur {NomUtilisateur}.", modele.NomUtilisateur);
						await _gestionConnexion.SignInAsync(utilisateur, isPersistent: false);
						return RedirectToAction("Index", "Tableaudebord");
					}

					foreach (var erreur in resultat.Errors)
					{
						_logger.LogWarning("Erreur lors de l'inscription pour l'utilisateur {NomUtilisateur} : {Description}.", modele.NomUtilisateur, erreur.Description);
						ModelState.AddModelError(string.Empty, erreur.Description);
					}
				}
				catch (Exception ex)
				{
					_logger.LogError(ex, "Erreur lors de la tentative d'inscription pour l'utilisateur {NomUtilisateur}.", modele.NomUtilisateur);
                    return RedirectToAction("Index", "Error");
                }
			}
			else
			{
				_logger.LogWarning("Échec de validation du modèle pour l'utilisateur {NomUtilisateur}.", modele.NomUtilisateur);
			}

			return View(modele);
		}
	}
}

Controllers/ContreIndicationsController.cs
using Microsoft.AspNetCore.Mvc;
using MedManager.Data;
using MedManager.Models;
using Microsoft.EntityFrameworkCore;
using MedManager.ViewModel.ContreIndication;
using System.Data.Common;
using Microsoft.AspNetCore.Authorization;

namespace MedManager.Controllers
{
    [Authorize]
    public class ContreIndicationsController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly ILogger<ContreIndicationsController> _logger;

        public ContreIndicationsController(ApplicationDbContext dbContext, ILogger<ContreIndicationsController> logger)
        {
            _dbContext = dbContext;
            _logger = logger;
        }

        public async Task<IActionResult> Index(string filtreAllergies, string filtreAntecedents, string OrdreTriAllergie, string OrdreTriAntecedent)
        {
            try
            {
                List<Allergie> allergies = await _dbContext.Allergies.ToListAsync();
                List<Antecedent> antecedents = await _dbContext.Antecedents.ToListAsync();

                OrdreTriAllergie ??= "";
                OrdreTriAntecedent ??= "";
                ViewData["NomAllergieParamTri"] = string.IsNullOrEmpty(OrdreTriAllergie) ? "nomAllergie_desc" : "";
                ViewData["NomAntecedentParamTri"] = string.IsNullOrEmpty(OrdreTriAntecedent) ? "nomAntecedent_desc" : "";

                if (!string.IsNullOrEmpty(filtreAllergies))
                {
                    allergies = allergies.Where(a => a.Nom.ToUpper().Contains(filtreAllergies.ToUpper())).ToList();
                }

                if (!string.IsNullOrEmpty(filtreAntecedents))
                {
                    antecedents = antecedents.Where(a => a.Nom.ToUpper().Contains(filtreAntecedents.ToUpper())).ToList();
                }

                switch (OrdreTriAllergie)
                {
                    case "nomAllergie_desc":
                        allergies = allergies.OrderByDescending(a => a.Nom).ToList();
                        break;
                    default:
                        allergies = allergies.OrderBy(a => a.Nom).ToList();
                        break;
                }

                switch (OrdreTriAntecedent)
                {
                    case "nomAntecedent_desc":
                        antecedents = antecedents.OrderByDescending(a => a.Nom).ToList();
                        break;
                    default:
                        antecedents = antecedents.OrderBy(a => a.Nom).ToList();
                        break;
                }

                var modele = (Allergies: allergies, Antecedents: antecedents);
                ViewData["TriActuelAllergie"] = OrdreTriAllergie;
                ViewData["TriActuelAntecedent"] = OrdreTriAntecedent;
                ViewData["FiltreActuelAllergie"] = filtreAllergies;
                ViewData["FiltreActuelAntecedent"] = filtreAntecedents;

                return View(modele);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Erreur lors de l'affichage des allergies et antécédents.");
                return RedirectToAction("Index", "Error");
            }
        }


        public async Task<IActionResult> Ajouter(string type)
        {
            List<Medicament> medicaments = await _dbContext.Medicaments.ToListAsync();
            var model = new ContreIndicationViewModel
            {
                Medicaments = medicaments,
                Type = type
            };
            return View("Action", model);
        }

        [HttpPost]
        public async Task<IActionResult> Ajouter(ContreIndicationViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.Type == "Allergie")
                    {
                        Allergie allergie = new Allergie
                        {
                            Nom = model.Nom
                        };

                        if (model.IdMedicamentsSelectionnes != null)
                        {
                            var medicamentsSelectionnes = await ObtenirMedicamentSelectionnes(model.IdMedicamentsSelectionnes);
                            foreach (var medicament in medicamentsSelectionnes)
                            {
                                allergie.Medicaments.Add(medicament);
                            }
                        }

                        await _dbContext.Allergies.AddAsync(allergie);
						TempData["SuccessMessage"] = "L'allergie a été ajoutée avec succès.";
						
                    }
                    else if (model.Type == "Antecedent")
                    {
                        Antecedent antecedent = new Antecedent
                        {
                            Nom = model.Nom
                        };

                        if (model.IdMedicamentsSelectionnes != null)
                        {
                            var medicamentsSelectionnes = await ObtenirMedicamentSelectionnes(model.IdMedicamentsSelectionnes);
                            foreach (var medicament in medicamentsSelectionnes)
                            {
                                antecedent.Medicaments.Add(medicament);
                            }
                        }
                        await _dbContext.Antecedents.AddAsync(antecedent);
						TempData["SuccessMessage"] = "L'antécédent a été ajouté avec succès.";
                    }
                    await _dbContext.SaveChangesAsync();
	
					return RedirectToAction("Index");
                }

				List<Medicament> medicaments = await _dbContext.Medicaments.ToListAsync();
                var modelView = new ContreIndicationViewModel
                {
                    Medicaments = medicaments,
                    Type = model.Type
                };
				return View("Action", modelView);

			}
            catch (DbException ex)
            {
                _logger.LogError(ex, "Une erreur est apparue pendant l'ajout de la contre-indication'.");
                return RedirectToAction("Index", "Error");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Une erreur innatendue est survenue.");
                return RedirectToAction("Index", "Error");
            }
        }

        public async Task<IActionResult> Modifier(int id, string type)
        {
            try
            {

                List<Medicament> medicaments = await _dbContext.Medicaments.ToListAsync();
                if (type == "Allergie")
                {
                    var allergie = await _dbContext.Allergies
                        .Include(a => a.Medicaments)
                        .FirstOrDefaultAsync(a => a.AllergieId == id);
                    if (allergie == null)
                        return NotFound();
                    var viewModel = new ContreIndicationViewModel
                    {
                        Id = allergie.AllergieId,
                        Nom = allergie.Nom,
                        Type = "Allergie",
                        Medicaments = medicaments,
                        IdMedicamentsSelectionnes = allergie.Medicaments.Select(m => m.MedicamentId).ToList() ?? new List<int>()
                    };
                    return View("Action", viewModel);
                }
                else if (type == "Antecedent")
                {
                    var antecedent = await _dbContext.Antecedents
                            .Include(a => a.Medicaments)
                            .FirstOrDefaultAsync(a => a.AntecedentId == id);
                    if (antecedent == null)
                        return NotFound();
                    var viewModel = new ContreIndicationViewModel
                    {
                        Id = antecedent.AntecedentId,
                        Nom = antecedent.Nom,
                        Type = "Antecedent",
                        Medicaments = medicaments,
                        IdMedicamentsSelectionnes = antecedent.Medicaments.Select(m => m.MedicamentId).ToList() ?? new List<int>()
                    };
                    return View("Action", viewModel);
                }
                return NotFound();
            }
            catch (DbException ex)
            {
                _logger.LogError(ex, "Une erreur est apparue pendant la modification de la contre-indication.");
                return RedirectToAction("Index", "Error");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Une erreur innatendue est survenue.");
                return RedirectToAction("Index", "Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Modifier(ContreIndicationViewModel model)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    if (model.Type == "Allergie")
                    {
                        var allergie = await _dbContext.Allergies
                                .Include(a => a.Medicaments)
                                .FirstOrDefaultAsync(a => a.AllergieId == model.Id);

                        if (allergie == null)
                            return NotFound();
                        allergie.Nom = model.Nom;

                        allergie.Medicaments.Clear();
                        if (model.IdMedicamentsSelectionnes != null)
                        {
                            var medicamentsSelectionnes = await ObtenirMedicamentSelectionnes(model.IdMedicamentsSelectionnes);
                            foreach (var medicament in medicamentsSelectionnes)
                            {
                                allergie.Medicaments.Add(medicament);
                            }
                        }
                        _dbContext.Entry(allergie).State = EntityState.Modified;

Controllers/ParametresController.cs
using MedManager.Data;
using MedManager.Models;
using MedManager.ViewModel.Compte;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MedManager.Controllers
{
    [Authorize]
    public class ParametresController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<Medecin> _userManager;
        private readonly ILogger<ParametresController> _logger;

        public ParametresController(ApplicationDbContext dbContext, UserManager<Medecin> userManager, ILogger<ParametresController> logger)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);

                if (user == null)
                    return NotFound();

                var medecin = await _dbContext.Users.FirstOrDefaultAsync(u => u.Id == user.Id);

                var modele = new CompteViewModel
                {
                    NomUtilisateur = medecin.UserName,
                    Prenom = medecin.Prenom,
                    Nom = medecin.Nom,
                    Adresse = medecin.Adresse,
                    Ville = medecin.Ville,
                    Faculte = medecin.Faculte,
                    NumeroTel = medecin.NumeroTel,
                    Email = medecin.Email,
                    MotDePasse = medecin.PasswordHash,
                };
                return View(modele);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Erreur lors de l'affichage des paramètres utilisateur");
                return RedirectToAction("Index", "Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Index(CompteViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var user = await _userManager.GetUserAsync(User);

                if (user == null)
                    return NotFound();

                var medecin = await _dbContext.Users.FirstOrDefaultAsync(u => u.Id == user.Id);

                if (medecin == null)
                    return NotFound();

                medecin.Nom = model.Nom;
                medecin.Prenom = model.Prenom;
                medecin.Adresse = model.Adresse;
                medecin.NormalizedEmail = model.Email;
                medecin.NormalizedUserName = model.NomUtilisateur;
                medecin.Ville = model.Ville;
                medecin.Faculte = model.Faculte;
                medecin.NumeroTel = model.NumeroTel;
                medecin.Email = model.Email;
                medecin.UserName = model.NomUtilisateur;

                var passwordHasher = new PasswordHasher<Medecin>();
                medecin.PasswordHash = passwordHasher.HashPassword(medecin, model.MotDePasse);

                _dbContext.Update(medecin);
                await _dbContext.SaveChangesAsync();

                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Erreur lors de la mise à jour des paramètres utilisateur");
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

Controllers/SupportController.cs
using Microsoft.AspNetCore.Mvc;

namespace MedManager.Controllers
{
	public class SupportController : Controller
	{
		public IActionResult Contact()
		{
			return View();
		}

		public IActionResult FAQ()
		{
			return View();
		}
	}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - MedManager</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
	<link href="https://cdn.jsdelivr.net/npm/tom-select@2.3.1/dist/css/tom-select.css" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
	<nav class="navbar">
		@if (User?.Identity?.IsAuthenticated == true)
		{
			<div class="nav-links ">
				<a class="custom-navbar-brand" href="#">
					<img src="@Url.Content("~/Images/gsbtransparent.png")" alt="Logo" style="height: 30px; margin-right: 3px;" />
					MedManager
				</a>
				<a asp-controller="Tableaudebord" asp-action="Index" class=" @(ViewContext.RouteData.Values["Controller"]?.ToString() == "Tableaudebord" ? "active" : "")">
					<i class="bi bi-house-door"></i> Tableau de bord
				</a>
				<a asp-controller="Patient" asp-action="Index" class=" @(ViewContext.RouteData.Values["Controller"]?.ToString() == "Patient" ? "active" : "")">
					<i class="bi bi-person-badge"></i> Mes patients
				</a>
				<a asp-controller="Ordonnance" asp-action="Index" class=" @(ViewContext.RouteData.Values["Controller"]?.ToString() == "Ordonnance" ? "active" : "")">
					<i class="bi bi-file-earmark-medical"></i> Mes ordonnances
				</a>
				<a asp-controller="Medicament" asp-action="Index" class=" @(ViewContext.RouteData.Values["Controller"]?.ToString() == "Medicament" ? "active" : "")">
					<i class="bi bi-capsule"></i> Médicaments
				</a>
				<a asp-controller="ContreIndications" asp-action="Index" class=" @(ViewContext.RouteData.Values["Controller"]?.ToString() == "ContreIndications" ? "active" : "")">
					<i class="bi bi-exclamation-triangle"></i> Contre-indications
				</a>
			</div>
			<div class="user-actions">
				<span class="username me-3">Bienvenue docteur @User.Identity.Name</span>
				<a asp-controller="Parametres" asp-action="Index" class="@(ViewContext.RouteData.Values["Controller"]?.ToString() == "Parametres" ? "active" : "")" data-bs-toggle="tooltip" title="Paramètres">
					<i class="bi bi-gear"></i>
				</a>
				<a asp-controller="Compte" asp-action="Deconnexion">
					<i class="bi bi-box-arrow-right"></i> Déconnexion
				</a>
			</div>
		}
		else
		{
			<a class="custom-navbar-brand" href="#">
				<img src="@Url.Content("~/Images/gsbtransparent.png")" alt="Logo" style="height: 30px; margin-right: 3px;" />
				MedManager
			</a>
			<div class="nav-links ms-auto">
				<a asp-controller="Accueil" asp-action="Index">
					<i class="bi bi-house-door"></i> Accueil
				</a>
				<a asp-controller="Compte" asp-action="Connexion">
					<i class="bi bi-box-arrow-in-right"></i> Login
				</a>
			</div>
		}
	</nav>

	<div class="container">
		<div class="toast-container position-fixed bottom-0 end-0 p-3">
			@if (TempData["SuccessMessage"] != null)

			{
				<div class="toast align-items-center border-0 bg-primary text-white" role="alert" aria-live="assertive" aria-atomic="true">
					<div class="d-flex">
						<div class="toast-body">
							<i class="bi bi-check-circle me-2"></i>@TempData["SuccessMessage"]
						</div>
						<button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
					</div>
				</div>
			}
		</div>

		<div class="toast-container position-fixed bottom-0 end-0 p-3">
			@if (TempData["ErrorMessage"] != null)

			{
				<div class="toast align-items-center border-0 bg-danger text-white" role="alert" aria-live="assertive" aria-atomic="true">
					<div class="d-flex">
						<div class="toast-body">
							<i class="bi bi-check-circle me-2"></i>@TempData["ErrorMessage"]
						</div>
						<button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
					</div>
				</div>
			}
		</div>


		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer>
		<div class="copyright">© 2024  - <img src="@Url.Content("~/Images/gsbtransparent.png")" alt="Logo" style="height: 30px; margin-right: 3px; margin-left:3px;" /> MedManager </div>
		<div class="footer-links">
			<a asp-controller="Support" asp-action="Contact">Contact</a>
			<a asp-controller="Support" asp-action="FAQ">F.A.Q</a>
		</div>
	</footer>

	<script src="https://cdn.jsdelivr.net/npm/tom-select@2.3.1/dist/js/tom-select.complete.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
	<script src="https://davidstutz.github.io/bootstrap-multiselect/docs/js/jquery-2.2.4.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels"></script>
	<script src="~/js/site.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<script>
	document.addEventListener('DOMContentLoaded', function () {
		var toastElements = document.querySelectorAll('.toast');
		toastElements.forEach(function (toastElement) {
			var toast = new bootstrap.Toast(toastElement);
			toast.show();
		});
	});
</script>

<script>
		document.addEventListener('DOMContentLoaded', function () {
		const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
		const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
	});

</script>